// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASPNETCore5HW1.Models
{
    public partial class sp_alterdiagramResult
    {
    }
}
